spring:
  application:
    name: smartparkingsystem
  datasource:
    url: jdbc:h2:file:./data/parkingdb
    driver-class-name: org.h2.Driver
    username: test
    password: test
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
parking:
  pricing:
    strategy: HOURLY
    hourly:
      MOTORCYCLE: 1.0
      BICYCLE: 0.5
      CAR: 2.0
      TRUCK: 3.0
    flat_rates:
      flatFee: 5.0
      hourlyRate: 1.5
secure:
  jwt-secret: y7e8F9aVx3GJv9Z1LwXn6s4PqkKfRb1j8Y+Tg3L6s2Q=